#include QMK_KEYBOARD_H
#include "version.h"

#define _BASE 0
#define _NAV 1
#define _GAMES 2

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT_ergodox(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_GRV, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_EQL, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LBRC, KC_LGUI, KC_NO, KC_LALT, KC_NO, KC_NO, KC_NO, KC_PSCR, TG(2), KC_SPC, KC_BSPC, MO(1), KC_BSLS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_MINS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_DEL, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_RBRC, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_RGUI, LGUI(KC_L), LCA(KC_DEL), HYPR(KC_NO), MO(1), KC_ENT, KC_SPC),
    [_NAV] = LAYOUT_ergodox(KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_NO, KC_NO, KC_INS, KC_PGDN, KC_UP, KC_PGUP, KC_HOME, KC_NO, KC_TRNS, KC_DEL, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, KC_TRNS, KC_MRWD, KC_MFFD, KC_MPLY, KC_VOLD, KC_VOLU, KC_NO, EE_CLR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_NO, KC_HOME, KC_PGUP, KC_UP, KC_PGDN, KC_NO, KC_F12, KC_END, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO),
    [_GAMES] = LAYOUT_ergodox(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_GRV, KC_HOME, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_PGUP, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_PGDN, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_G, KC_LGUI, KC_NO, KC_LALT, KC_M, KC_B, KC_MPLY, KC_MFFD, KC_TRNS, KC_SPC, KC_SCRL, KC_END, KC_BSLS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_MINS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_DEL, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_RBRC, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_LGUI, KC_NO, KC_NO, KC_VOLU, KC_VOLD, KC_ENT, KC_SPC)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)



